### PR TITLE
Add optional config setting to trust all input

### PR DESCRIPTION
**Pull request by trufa**
Add `trustAllEvents` optional property that when set to true will allow non trusted events.

This is useful for e2e tests and automating software.

### CODE REVIEW

**Comment by trufa** [comment]
I just realized, this adds a feature, should I bump the version to 8.4.0?

**Comment by ornicar** [comment]
Please add comments to config.ts and state.ts, where settings are documented. I'll bump the version.

**Comment by trufa** [comment]
@ornicar I apologize for the oversight! I've added the comments.

**Comment by trufa** [comment]
@ornicar Thanks for the quick action!

**Pull request merged**
