### PR TITLE
chore: remove rollup

### LINKED ISSUE #250: Use esbuild instead
(ref: [chessground packaged files](https://www.npmjs.com/package/chessground?activeTab=explore))

While I was digging around the chessground code, I noticed that the rollup build system isn't used for external purposes (not published to the NPM package) and barely serves a place internally. The max purpose it serves, rather, is that it *tests* chessground for recursive modules, and bundles for the internal demo.

If this is the case, it seems more fair to use esbuild as a check system rather than rollup.

### PR DESCRIPTION
**Pull request by LeoDog896**
Removes redundant rollup build. Now that the `dist` folder is freed, moves the main files over to `dist`.

Other changes are purely formatting changes made with `npm run format`.

### CODE REVIEW

**Comment by niklasf** [comment]
This bundle is currently used over at https://github.com/lichess-org/lila/blob/master/public/javascripts/vendor/chessground.min.js. We first need to update lila to produce the bundle in a different way, if we want to remove this here. Doing that instead of checking the compiled file into source control definitely makes sense, though.

**Comment by LeoDog896** [comment]
Sounds good 👍, if you need any help on the lila side do let me know.

**Comment by niklasf** [comment]
@schlawg Any oppinion on this? I see that [lichess-pgn-viewer also makes rollup bundles](https://github.com/lichess-org/pgn-viewer/blob/bc27576f3bfaf70991f32bdbe947cc3eeeb46f6b/package.json#L46), but does not include them in the npm package.

**Comment by LeoDog896** [comment]
I did some digging and it seems to be the way lila does it legacy. I'll make a refactor PR to bundle *all* necessary dependencies, which:
- should decrease bundle size (and therefore increase performance)
- open us to code splitting (woo! js perf!)

**Comment by schlawg** [comment]
I just now saw your note Niklas.  I'm not familiar with chessground or this issue but I'm sure it's fine, let me know if you need anything LeoDog.

**Comment by LeoDog896** [comment]
The issue is a [much more deeply rooted problem](https://github.com/lichess-org/lila/pull/12394#issuecomment-1452152283) in lila that comes down to how lila optimizes dependencies.

**Comment by schlawg** [comment]
I'm all for fixing deep rooted problems!  Keep in mind that for any major changes you have in mind, you'll need to _demonstrate_ concrete benefits that outweigh the churn cost.  Keeping sync with a notion of best practices is commendable but not even close to sufficient.

**Comment by LeoDog896** [comment]
I'll close this for now.

**Pull request closed without merging**
